# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Tkr3Y2a3T+JPTGxsBE0qLGV77lsk//Oz+M38O7JgNRxAmT6JgR/s0dRbauaf+NjS5Fa9lxU1/TtDDeU3/iAkmhod7nWZFneDIg2CKrwWXZntAIzN9rasFSwb/cqIr0CmLtx82Eiz3HD+aJC0GWbAJ6d/XRf9Gwljs1Lp+yVuJLGCQWSX3hBGumJ/EZY5ru81oDVCYLnFsBwad8/wkQnKaH+xwn6w1KPyT4dwW+oP9ASdhEy80DL9pwmYPm8PGzZiarDu7ssYePbv2/TYTYp/9MlQzsC+YoeKjPqoUEhGo+752S4n9qVGC0zJHqkMJQ72t0A1wUw/Lyfq7HZJRWhcGp0/yCc4eUaIEaxKRq9qqaWTSCiytowsiYlIM+7f1mnPnAX3/1B2cerHOM9PWYxC++klRMsX7yiv2lj93HX8UHDrgJu5tLxIa/aZnsFyTEBCIBP/mNMIr8pZL/y8Uk0m6ZDUCAd0ypxSNG2dhgri8qSC40EYTkumOufVNf21K0IJyR+ypou85OlWwlTliGnVWDD42gvcCmQwHLzlg1ZWjOGd3zuVD6IVUf0dYRTnHqExR1yP8kyKhnJg9AhU7dIxXzirc9mObqRWPXbRfEfhW5gJGiC3Pe90sNBsyyLNe9iOsao11xwS0MCiMdrD/AkhHmCvMSFdc4egELqTQtlKT3U="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
