# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ayG47GjZ+4zJux0qdRFFTtdLOV2DqQY7+1p8NyPkU/RgcUthvAilinRoihukFiTqV8i57fTXGNy4UBuq/XdamTgjgfrlaBGk8Q86DYV/jRyCNfDTV2Z8q2ybXtthXIqJYu01rI8/uWbyPiFP1miCoM/bUvmZMmz/F57xa/3lKK+hylv32rhWhfWKa7w+ivxklS7U8DvitVSIbOR6pAHCXoZajYjS5FJe4Rk4Z8gc/ixtkAr6hspOLvB6MELaCwL9P1EHVYdFmmeVxb48X+eBKxaQLZfcCFaYNbme/oSJlNZ0RvDxEAfalLQUWzKiJ+qrjAfUongsLszVVDnzUKw/A1BMSvpDCRjGApjfH9hhbQMuZ2wdNy4h/khpUOPNBXMHJh2jmKssEwzYhkth5Q5bELc2Cwv1fRyw/urq4M8cUIY41W/HHGeWDA7aCaW649oWl2JEZJhMSrhpKcNwXbji7oZQjWHXkuQTdC0Sru7UNPzHaTWfc/YF4Zz6gdKygmJBn15D7BTihCsAOn5TdvDGPS9s37docPZ/p/RNo6MGjexFaoW54xSQ7ROyzzo4lSifqmT9BJrocWvHXOmwYEbgBPvUpoueuXf2SmiirlJtPbBHAy7WZJzbE68J2inWeWwMvfUxvRypcexqQsWrz58xXNV9mBVXncq/8qlQFKY64hY="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
