travis:
  secure:
    BINSTAR_TOKEN: ayG47GjZ+4zJux0qdRFFTtdLOV2DqQY7+1p8NyPkU/RgcUthvAilinRoihukFiTqV8i57fTXGNy4UBuq/XdamTgjgfrlaBGk8Q86DYV/jRyCNfDTV2Z8q2ybXtthXIqJYu01rI8/uWbyPiFP1miCoM/bUvmZMmz/F57xa/3lKK+hylv32rhWhfWKa7w+ivxklS7U8DvitVSIbOR6pAHCXoZajYjS5FJe4Rk4Z8gc/ixtkAr6hspOLvB6MELaCwL9P1EHVYdFmmeVxb48X+eBKxaQLZfcCFaYNbme/oSJlNZ0RvDxEAfalLQUWzKiJ+qrjAfUongsLszVVDnzUKw/A1BMSvpDCRjGApjfH9hhbQMuZ2wdNy4h/khpUOPNBXMHJh2jmKssEwzYhkth5Q5bELc2Cwv1fRyw/urq4M8cUIY41W/HHGeWDA7aCaW649oWl2JEZJhMSrhpKcNwXbji7oZQjWHXkuQTdC0Sru7UNPzHaTWfc/YF4Zz6gdKygmJBn15D7BTihCsAOn5TdvDGPS9s37docPZ/p/RNo6MGjexFaoW54xSQ7ROyzzo4lSifqmT9BJrocWvHXOmwYEbgBPvUpoueuXf2SmiirlJtPbBHAy7WZJzbE68J2inWeWwMvfUxvRypcexqQsWrz58xXNV9mBVXncq/8qlQFKY64hY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
