travis:
  secure:
    BINSTAR_TOKEN: Uuo7EGsm+iRbgmMxwK15O3adJX1VGZDrTyggRbxkjqnIb2TS6msi0o8JPvv1AtNx5xpzYO6F9usVnuY2Qep8QJ3GC5CXnahnyT/z+pu4ctr7g2ouQVqvCdY67O7xB7EPuCvb3tE2DpvNwuHrUzrdNplMq+NzenNrBKP3BKqDPQB0pdRWboNEwMGz+jCT1SCjACbmR4wbQdHs8ATIlrSR/bM421fcVwmlY5Wxq6aoCLZ3oa6G7imrkTiw81sdVy/oGyzN36FQf0Giy9eb/GhGkLavO5NzkPGjt0bwT9jy32swUyANrjHodt1sr8iOTNPAU+gvBwZ2erOiyNKfLUlBPAbaZhLLULk9rW+WSuhwEtwMPSrQnQC+RzjcwDOc6W0inx+xKJNGwJSBrN35YsMcBNpfKca69njKiVMD3VCXD0Qe62XQEQLYT/jFwLfJThHCWMDgRgV+tklW9aPikQVqSy6XmoTogDDyLyT4rSyxwnDLd6olIcZIYUudEXLy50jzZzj5gPt+7nmkHWXpZoyQhnCkUAYo05nrrk5nxVCQCITkaDfaV8ovz662OmUuD37ePZedFu9/DLWyVqsFQLOIyyHU6tB/ad9ggGMo27xH9O6FJFv/7VBqhDUrdSHv4StP/2SfGHmiE286laI34js8xU+xqOzPLunJJnx7Gi9BdFI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
